### ISSUE TITLE
FUD

### ISSUE THREAD

**Issue by kmsufo** [No-Bling/DOTA#41]
https://www.reddit.com/r/DotA2/comments/ghycj1/a_nineyearold_account_just_blocked_for_a_month/

**Comment by AveYo** [comment]
People have tried to use this mod as a scapegoat for their actually cheating and other abusive behavior over the years.

There is zero proof of anybody ever being banned for using it.

It's a passive resource replacement for cosmetics, with no gameplay value (and since Valve stopped believing in glance-value you can't use that as an argument). No reactive scripts / panorama js hooks / dll or process manipulation,  no pumpking trees and tower ranges either.

Delete your lies and apologize.
