### ISSUE TITLE
No-Bling not working after new battle pass update!

### ISSUE THREAD

**Issue by KerzaGG** [No-Bling/DOTA#43]
Now when you open the game after using the no-bling mod, dota 2 crashes with this error https://i.imgur.com/y9OcHXr.png panorama::RequiredCallFailed(): unable to find child 'GuildsContainer' in layout file 'panorama\layout\dashboard.xml'

In order to fix it just delete the tempcontent launch option from dota 2 but that makes the mod stop working too :(.

Hope @AveYo can check this out soon enough.

**Comment by KerzaGG** [comment]
If anyone finds something to make it work please let me know, I am assuming it has something to do with the Guild system that came with this battlepass update.

**Comment by robbyz512** [comment]
Import the file pak01_dir into VRF
https://vrf.steamdb.info/
Extract everything, delete panorama folder, then repack it. 

Although all the new cosmetics will still show in-game unless you manually edit them out 1 by 1. Which I might end up doing @AveYo isn't updating.

**Comment by KerzaGG** [comment]
@robbyz512 Thank you for the answer!

Do I need to edit the new cosmetic files with VRF too? I never used the software so I have to learn how to use it.

Also do you know if it is possible to edit the minimap heroes too? https://github.com/No-Bling/DOTA/issues/37 From this issue I learned that I had to delete a file (which I can't remember which one, was long time ago) to make Snapfire and Void minimap icons appear again, but also now the arcana icons show on both minimap and top hero bar in-game. Is this possible to do with VRF?

**Comment by robbyz512** [comment]
No you don't need to edit the cosmetic items to fix the crashing error, you just have to delete the panorama folder. I was only mentioning that the new battle pass cosmetics will not be filtered by no-bling.

As for the minimap icons that that file on #37 has a missing ogre icon so to get a proper one you'll need to use dotamodkit to convert the 
"materials\vgui\hud\minimap_hero_sheet_psd_3529892avtex_c" file to TGA, edit it in photoshop then back to vtex and then use resourcecompiler in command line to compile it so it's usable. This ain't easy and it's off-topic just focus on fixing your crash error for now I think.

**Comment by heyimrendy** [comment]
Here latest normalize minimap if anyone wants the normal minimap.
https://mega.nz/file/dXBXiCaL#gWgaCYRwzl1qD-uZg5DfAG0Py-CpJ-D3K-xpqIxjORc

Will upload tweak version of dota dashboard if I have time.

**Comment by KerzaGG** [comment]
@robbyz512 I meant that I want to try and do the cosmetic things and try to fix this mod myself since I  like it a lot and always use it since it was out but I actually don't know how so I'm looking for guides or something so I can learn how to edit the stuff and fix the mod

@heyimrendy when you say "Will upload tweak version of dota dashboard if I have time." does that fix the panorama error?

**Comment by light6486** [comment]
I'm getting this error.
https://i.imgur.com/QiFR4Po.jpg

**Comment by heyimrendy** [comment]
> @heyimrendy when you say "Will upload tweak version of dota dashboard if I have time." does that fix the panorama error?

I dont know what panorama error since im not playing dota anymore, only checking stuff to see what's new.

So here the dashboard tweak if anyone interested. During test on low spec pc my CPU shows no spike because animated videos was turn off. Related workaround if you dont feel comfortable to install 3rd party VPK https://old.reddit.com/r/DotA2/comments/gqp2iv/remove_dota_2_intro_animation_and_reduce_lag_on/
Assets based on client version 4212(27 May 2020) also include normalize minimap. What did I remove?

- [x]  Main menu skeleton king promo, you can still click the button to watch the promo video.
- [x]  Animated video assets in the middle, go to compendium website and purchase compendium button left intact. No idea if this will be buggy since I dont have compendium to test, it has different layout for compendium users.
- [x] Animated background video assets(this is unnecessary since Valve push a patch to only play on non-high settings).

Download:
- Compiled VPK version, just drag and drop https://mega.nz/file/xK513LAS#vCzRBVGULNOqhghsqDb_5A5tKxdu-2WZdlLTEnytBvM
- Non compiled VPK version if you need to add your own mods before compile them https://mega.nz/folder/xKwniKDK#QD2_l4SHT8jwpOVS4PfKgw
- Raw .xml files if you interested to change stuff on your own https://mega.nz/folder/9C513bzb#UnLpLLYaubcUVm_8RnU7-g

**Comment by robbyz512** [comment]
Muted the files for new chat wheel messages if anyone wants them 
[sounds.zip](https://github.com/No-Bling/DOTA/files/4687362/sounds.zip)

**Comment by robbyz512** [comment]
Muted sounds for new chat wheel if anyone wants.
[sounds.zip](https://github.com/No-Bling/DOTA/files/4687747/sounds.zip)

**Comment by KerzaGG** [comment]
Thanks, I don't think AveYo is going to touch this mod anymore so I hope someone at some point wishes to fork this and update it on their own.

**Comment by AveYo** [comment]
But in particular, you are mistaken! I did resume working on it - a full rewrite in c# so that it can also be used via mono in linux and probably macos - just had to halt since a little bird told me new battlepass changes are going to be significant. Which they are.

**Comment by KerzaGG** [comment]
@AveYo I am so glad I was mistaken, hope everything is going well for for you.

**Comment by Lethalmathematix** [comment]
Hail based @AveYo!!

Correct me if my assumption is wrong, but the way the mod works is by replacing (or maybe pointing the path of) the "hattened" version of the hero model/effects to the default version.

Assuming the above is true, would it be possible to make a generic script that does this even for the new hats/heroes?

I guess the limitation here would be that the directory structure in the .vpks get changed/moved about.

**Comment by AveYo** [comment]
Actually it has been doing just that for years! 
If it were completely hard-coded, it would not work without updates after most patches 💇‍♂️
It's only the pre-made builds that remain outdated, while the script has generated a fresh build incorporating changes for new cosmetics as they come.

The approach is to block all first, and whitelist later. 
The updates have mostly been about fine-tuning the whitelist (filters) specially around TI when major new content hits, with not much changes over the core script that dynamically parses items_game.txt definitions.  

Due to new personas & etc. the approach is going to be a little different. Will see how well received the changes are going to be (basically you must run the script more often / before starting DOTA).
Choices are also gonna be fewer than before, at least in the beginning.

**Comment by vannessqn** [comment]
@AveYo hey dude thanks for the work, your mod help me increase great fps, hope we can get some update soon

**Comment by KerzaGG** [comment]
Yeah this mod is best mod

**Comment by KerzaGG** [comment]
Personally I think this is the best mod ever. For me it is because it makes the game have that "dota 1 feel" that does not matter the match, there is not going to be a new cosmetic that change spells and that can make a fight harder to understand what happened. I love this mod.

**Comment by meatgrind89** [comment]
I hope @AveYo fix this soon because I don't know what to do with those files that others posted lol

**Comment by AveYo** [comment]
Status update:  
I've finished all the core C# program!
~ Reimplemented vpk writing and resource handling
~ Reimplemented keyvalue parsing to enhance querying
~ Reimplemented Options and Choices snippets
~ Scratched some stuff and redid them to work in MONO (linux)

Reimplemented the mod logic
~ now mainly a items_game.txt editor with far less direct file replacements
~ can disable even those pesky stuff like personas that can't just be resource-replaced  
~ more future proof due to fewer hard-coded stuff to break on a new patch (hero icons pff)  
~ better user exceptions (filters);   

@meatgrind89 - even in the old version you could have added filter for specific items to exclude   
but due to the nature of the mod it had mixed results.  
Now, you can filter an item id to keep all it's visuals, or keep the model - it works reliably.    
Can even replace all effects from an item with those of another item!   
(works only in demo / local game but it's cool to look at crazy mixes even from one hero to another)  

So, alive. Just slow. Because my life is very hectic these months..

**Comment by KerzaGG** [comment]
@AveYo Hope everything is going well for you and life stops being hectic, even tho' this year has been so weird for everyone....

I read your update and It seems we are going to be able to modify files easier after each dota 2 update? It sounds like it, or I am confusing myself :(

**Comment by AveYo** [comment]
**Plot twist**: Gaben incentivized me not to release an update until TI10 gets to $20,000,000

**Comment by Lethalmathematix** [comment]
That's so ***ben. :^)

That's some awesome progress!!! :D :D :D

> Actually it has been doing just that for years!
> If it were completely hard-coded, it would not work without updates after most patches 💇‍♂️
> It's only the pre-made builds that remain outdated, while the script has generated a fresh build incorporating changes for new cosmetics as they come.
Ah. I figured otherwise since we had those issues with the minimap hero icons. :p
But I guess just that must be a hardcoded sprite kind of image.

> Due to new personas & etc. the approach is going to be a little different. Will see how well received the changes are going to be (basically you must run the script more often / before starting DOTA).
> Choices are also gonna be fewer than before, at least in the beginning.
🤞🤞🤞

**Comment by KerzaGG** [comment]
> **Plot twist**: Gaben incentivized me not to release an update until TI10 gets to $20,000,000
> So get them BP levels faster!

GAAABBBEEEEENNNNNN WHHHYYYYY

**Comment by nobling** [comment]
Yo @AveYo its already above $20M, can we get the latest release now? We really need that 100%, 40fps kills me so bad. Thanks in advance! Love your work truly!

**Comment by IneedNoBlingMode** [comment]
Hello @AveYo , WeNeedNoBlingMode , when u will upload an update ?

**Comment by ilyasovivan** [comment]
@AveYo, Register at patreon.com. I think many people will support you. And you will have more motivation.

**Comment by nobling** [comment]
Sorry guys, I think it's over. We wont have new update anymore. Thank you guys, esp AveYo for this awesome mod, but I think it's safe to say goodbye to Dota 2. No update means wont able to play that beautiful game anymore, sad life. Hope good things happen for all of us guys in the future. Farewell 😞

**Comment by AveYo** [comment]
**Failure to Launch. Failure to Deliver. I have become Valve time.**   
Having so many interruptions did not help development. Such is life, food on the table is paramount and PC time is luxury.  
I set out to do a simpler builder than the old one and ended up doing something even more complicated.   
And there's so much visual diarrhea this year :(
I've added filters, filters, filters everywhere. Some work, some don't. It's gonna be a mess.   
**But the wait is over!**   
In a few hours I will upload the new script. Feel free to provide feedback afterwards to fix / improve it.

**Comment by AveYo** [comment]
give or take :)

**Comment by KerzaGG** [comment]
@AveYo Patience has been worth every second AveYo, thank you very much for your hard work, your no-bling  users love you very much.

**Comment by AveYo** [comment]
The new framework did pay out in the end, as it's now easier to customize for both me and for users.   
Next update will improve filters a bit - something to conveniently toggle styles without copy pasting the whole visuals section in replace_item rules.

**Comment by KerzaGG** [comment]
Whatever it takes AveYo we support you. We potatoes thank you for being the hero we need!
