### ISSUE TITLE
Certain abilities that change hero model might not be GlanceValued(tm)

### ISSUE THREAD

**Issue by Lethalmathematix** [No-Bling/DOTA#53]
Just played a game against this Undying where his ult form is not glancevalued.

And also spectated a game with Christmas-tree tiny who still had his decor on in the summer.

<img width="1440" alt="Screenshot 2020-07-14 at 2 45 44 AM" src="https://user-images.githubusercontent.com/10322629/87354885-fe393500-c57c-11ea-8153-ad7cb61795ce.png">

**Comment by AveYo** [comment]
I suspect hero replacement type of resources are overridden by the game coordinator just like it does for io arcana for example.  
If that's the case, I will fallback to hard replacements of those resources.  
Tomorrow I'm back in full force working on it.  
Would help if you give me the match id so I can download it

**Comment by Lethalmathematix** [comment]
Undying: 5511807237

Tony model and Furion treants: 5512223382

**Comment by Lethalmathematix** [comment]
Also, check out Lycan ult and wolves (and also 'ol Tony) here: 5512458404

**Comment by AveYo** [comment]
I know, the script simply whitelists such models and the glancevalue option does not properly address that.  
Now this is the kind of input I need because my testing possibilities are very limited, thank you!  
No need for further examples or other such bug reports until after the next update.   
I am working on it right now.
