### ISSUE TITLE
Is there any way to download previous patch version?

### ISSUE THREAD

**Issue by heboq** [No-Bling/DOTA#55]
Just discovered that glancevalue doesn't work properly in new patch but i don't have old patch version already :(

**Comment by Mackzwellz** [comment]
https://github.com/No-Bling/DOTA/archive/7e14f7b933fb4be932362f1926700b04a6848e8b.zip

Download this one, it's the one that came out after TI9 and it was the last one before this year's changes.
You can also use it alongside the new version by using 2 separate files, see my description here: https://github.com/No-Bling/DOTA/issues/47#issuecomment-657150501

Bear in mind there might be issues, e.g. I think I've seen most of shaker's Planetfall arcana not being displayed, and an "ERROR" model showing up instead. IDK if it's caused by my "mixed" setup or by this version alone though.

**Comment by d353rv3b** [comment]
Thank you! Yea, i also had this issue with shaker arcana's . 

Btw i had something like empty transparent circles [(screen)](https://i.imgur.com/oOcK6X4.jpg) instead of minimap's icons of certain heroes (viz Void Spirit, Snapfire and all personas (like qop am, etc.) in old patch. 
In new patch they are displayed i guess (at least void and snapfire, i haven't checked personas yet). 
Is there anything I can do to fix it, using old patch?

**Comment by Mackzwellz** [comment]
Conflicting files override each other. You can try swapping names of files (pak01_dir and pak02dir) and see in which order changes get applied.

For solution to icons not showing up, read this issue's discussion: https://github.com/No-Bling/DOTA/issues/37

New No-Bling version isn't finished yet, that's why.

You can enable everything in new No-Bling, but you should disable at least HeroTweaks in old No-Bling. If you leave it enabled, you will have some animations missing/broken, e.g. with Rubick arcana.
I'm not sure how to fix all of these issues. You can try whitelisting (allow to be displayed) some of the cosmetics that have issues, and see if it works. I know it's possible to whitelist stuff in both old and new No-Blings, but the process is different in both, so you will have to look for examples in[ description of old No-Bling](https://github.com/No-Bling/DOTA/tree/7e14f7b933fb4be932362f1926700b04a6848e8b), [older already closed issues](https://github.com/No-Bling/DOTA/issues?q=is%3Aissue+is%3Aclosed) or in old reddit threads about No-Bling.

**Comment by AveYo** [comment]
Well I've sorted this shit out a bit and will push an update later - a hybrid items_game.txt mod for the particles and other stuff and old-fashion replacement for the models. Totally fubar'ed filters somewhere in the process I don't recognize this mod anymore 💇‍♂️
