### ISSUE TITLE
Script doesn't work if game is installed in a differect directory

### ISSUE THREAD

**Issue by ghost** [No-Bling/DOTA#61]
Hi,
I can't seem to get this working since Dota 2 is installed on a different directory than Steam.
I keep getting the following error after the splash art:
`System.IO.FileNotFoundException: Could not find file 'c:\Installed Software\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk`
The actual installation folder is in D:\Games\SteamLibrary
Any workarounds?

**Comment by jsphwllng** [comment]
[Here](https://github.com/No-Bling/DOTA/blob/master/No-Bling-builder.bat) you can specify which folder dota is installed in at line 4.

**Comment by tmrouvier** [comment]
Hi,
Over-riding STEAMPATH does not seem to fix the problem : 
`System.IO.FileNotFoundException: Le fichier 'd:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\pak01_dir.vpk' est introuvable.`
Steam is installed on my D\ drive, DOTA is installed on my F\ drive.
I tried putting (l.4) :
`set "STEAMPATH=F:\Program Files (x86)\Steam"`
but it gets overwritten because that's not where _"STEAMPATH\steamapps\libraryfolders.vdf"_ is located.

Problem seems to be that vpkmod.exe requires path to both libraryfolders.vdf and dota2_beta to function, but only takes STEAMPATH as argument.

**Comment by tmrouvier** [comment]
Ok so I added:
`GAMEPATH = "F:/Program Files (x86)/Steam/steamapps/common/dota 2 beta/game";`
at line 2087 of vpkmod.cs and it seems to be working.
Suboptimal, but at least I can get it running.

**Comment by Borjec1** [comment]
By the way you can fix it using command in No-Bling-builder.bat

`set "GAMEPATH=C:\SteamLibrary\steamapps\common\dota 2 beta\game"`
