### ISSUE TITLE
This Powerful Engine is not Working for me

### ISSUE THREAD

**Issue by csbmjrs2** [No-Bling/DOTA#66]
I activate all the functions, especially the one that leaves the Spec clean.
However, it is not working. It hasn't changed at all.
I add "-tempcontent", but the spec remains the same, everything still the same
I use the W10 Lite 64bit system

**Comment by robbyz512** [comment]
Have you checked if the vpk file is created?
> Steam\steamapps\common\dota 2 beta\game\dota_tempcontent\pak01_dir.vpk

And if it is make sure that you don't have the same vpk file in the mods folder, Since if the mods folder vpk file has it's own items_game.txt it will use that one instead.
> Steam\steamapps\common\dota 2 beta\game\mods\pak01_dir.vpk

Also the UI design is weird, make sure to click the options you want to use and that they are highlighted white before you click OK.
![32132132321](https://user-images.githubusercontent.com/48497779/98878580-37c27400-247b-11eb-809a-b8c1e350b61e.png)

**Comment by csbmjrs2** [comment]
> Have you checked if the vpk file is created?
> 
> > Steam\steamapps\common\dota 2 beta\game\dota_tempcontent\pak01_dir.vpk
> 
> And if it is make sure that you don't have the same vpk file in the mods folder, Since if the mods folder vpk file has it's own items_game.txt it will use that one instead.
> 
> > Steam\steamapps\common\dota 2 beta\game\mods\pak01_dir.vpk
> 
> Also the UI design is weird, make sure to click the options you want to use and that they are highlighted white before you click OK.
> ![32132132321](https://user-images.githubusercontent.com/48497779/98878580-37c27400-247b-11eb-809a-b8c1e350b61e.png)

Thanks for the Answer, i`ll show some prints about my problem.

I use this command to initialize the dota: +map_enable_background_maps 0 -novid -console -high -32bit +cl_showfps 1 -tempcontent 

its DX9

i choice everything > 
"No-Bling"
{
	"sel"		"Couriers,Wards,Heroes,Wearables,Abilities,GlanceValue,Taunts,SoundBoard,Loadout,Potato"
}
"

Spec still with the aura :LLLL
